---
# (c) Copyright IBM Corporation 2023
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

# Playbook file: playbooks/mq_delete_svrconn_channel.yml

# This playbook is run via the z/OS Cloud Broker MQ resources sub-operator to delete a svrconn channel.
- name: Delete a server connection channel
  hosts: all
  collections:
    - ibm.ibm_zos_core
# For playbooks that are run via a z/OS Cloud Broker sub-operator, it is required that gather_facts is disabled.
  gather_facts: no

# Environment, Queue Manager and Channel specific variable files.
  vars_files:
    - vars/env.yml 
    - vars/mq_qmgr.yml
    - vars/mq_svrconn.yml

# Environment variables
  environment: "{{ environment_vars }}"

  tasks:
    - name: Issue DELETE svrconn CHANNEL command and register the output
      zos_operator:
        cmd: "{{ mq_qmgr_cpf }} DELETE CHANNEL({{ mq_channel_name }})"
        verbose: false
      register: delete_svrconn_channel_output

    - name: Display output from DELETE svrconn CHANNEL command
      debug:
        msg: "{{ delete_svrconn_channel_output.content }}"

    - name: DELETE svrconn CHANNEL command succeeded
      debug:
        msg: "Delete svrconn channel {{ mq_channel_name }} succeeded"
      # CSQ9022I - normal completion message
      when: delete_svrconn_channel_output.content is search("CSQ9022I")

    - name: DELETE svrconn CHANNEL command failed
      fail:
        msg: "Delete svrconn channel {{ mq_channel_name }} failed"
      when: delete_svrconn_channel_output.content is not search("CSQ9022I")
...