---
# (c) Copyright IBM Corporation 2023
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

# Playbook file: playbooks/mq_define_qalias.yml

# This playbook is run via the z/OS Cloud Broker MQ resources sub-operator to define an alias queue.
- name: Define an alias queue 
  hosts: all
  collections:
    - ibm.ibm_zos_core
    - kubernetes.core
# For playbooks that are run via a z/OS Cloud Broker sub-operator, it is required that gather_facts is disabled.
  gather_facts: no

# Environment, Queue Manager and Queue specific variable files.
  vars_files:
    - vars/env.yml 
    - vars/mq_qmgr.yml
    - vars/mq_qalias.yml

# Environment variables
  environment: "{{ environment_vars }}"

  tasks:
    - name: Build DEFINE QALIAS command
      set_fact:
        define_qalias_cmd: "{{ mq_qmgr_cpf }} DEFINE {{ mq_queue_type }}({{ mq_queue_name }}) DESCR('{{ mq_queue_descr }}') TARGET({{ mq_target_queue_name }}) TARGTYPE({{ mq_target_type }}) {{ mq_queue_replace }}"

    - name: Add LIKE attribute if like queue name is specified
      set_fact:
        define_queue_cmd: "{{ define_qalias_cmd }} LIKE({{ mq_like_queue_name }})"
      when: mq_like_queue_name

    - name: Issue DEFINE QALIAS command and register the output
      zos_operator:
        cmd: "{{ define_qalias_cmd }}"
        verbose: false
      register: define_qalias_output

    - name: Display output from DEFINE QALIAS command
      debug:
        msg: "{{ define_qalias_output.content }}"

    - name: DEFINE QALIAS command succeeded
      debug:
        msg: "Define qalias {{ mq_queue_name }} succeeded"
      # CSQ9022I - normal completion message
      when: define_qalias_output.content is search("CSQ9022I")

    - name: DEFINE QALIAS command failed
      fail:
        msg: "Define qalias {{ mq_queue_name }} failed"
      when: define_qalias_output.content is not search("CSQ9022I")

    - name: Issue DISPLAY QALIAS command and register the output
      zos_operator:
        cmd: "{{ mq_qmgr_cpf }} DISPLAY {{ mq_queue_type }}({{ mq_queue_name }})"
        verbose: false
      register: display_qalias_output
      when: define_qalias_output.content is search("CSQ9022I")

# The output from the display command can be viewed in the Red Hat OpenShift Console.
    - name: Display output from DISPLAY QALIAS command
      debug:
        msg: "{{ display_qalias_output.content }}"
      when: display_qalias_output

# The following config map code could not be verified on our test machine so it has been commented out. 
# The intent of the code was to save the output of the display command to a config map so that the map 
# could be viewed in the Red Hat OpenShift Console.  
#
#    - name: Create configmap for output of DISPLAY QALIAS command
#      k8s:
#        state: present
#        definition:
#          apiVersion: v1
#          kind: ConfigMap
#          metadata:
#            name: alias_queue_map
#            namespace: default
#          data: "{{ display_qalias_output.content }}"
...