---
# (c) Copyright IBM Corporation 2023
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

# Playbook file: playbooks/mq_delete_queue.yml

# This playbook is run via the z/OS Cloud Broker MQ resources sub-operator to delete an alias queue.
- name: Delete an alias queue  
  hosts: all
  collections:
    - ibm.ibm_zos_core
# For playbooks that are run via a z/OS Cloud Broker sub-operator, it is required that gather_facts is disabled.
  gather_facts: no

# Environment, Queue Manager and Queue specific variable files.
  vars_files:
    - vars/env.yml 
    - vars/mq_qmgr.yml
    - vars/mq_qalias.yml

# Environment variables
  environment: "{{ environment_vars }}"

  tasks:
    - name: Issue DELETE QALIAS command and register the output
      zos_operator:
        cmd: "{{ mq_qmgr_cpf }} DELETE {{ mq_queue_type }}({{ mq_queue_name }})"
        verbose: false
      register: delete_qalias_output

    - name: Display output from DELETE QALIAS command
      debug:
        msg: "{{ delete_qalias_output.content }}"

    - name: DELETE QALIAS command succeeded
      debug:
        msg: "Delete qalias {{ mq_queue_name }} succeeded"
      # CSQ9022I - normal completion message
      when: delete_qalias_output.content is search("CSQ9022I")

    - name: DELETE QALIAS command failed
      fail:
        msg: "Delete qalias {{ mq_queue_name }} failed"
      when: delete_qalias_output.content is not search("CSQ9022I")
...