---
# (c) Copyright IBM Corporation 2023
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

# Alias Queue variables - these variables are used when creating an instance of an Alias queue.
mq_queue_name:
mq_queue_descr: ' '
mq_queue_type: QALIAS
mq_target_type: QUEUE
mq_like_queue_name: ""
mq_queue_replace: REPLACE
...