---
# (c) Copyright IBM Corporation 2023
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

# Playbook file: playbooks/mq_define_svrconn_channel.yml

# This playbook is run via the z/OS Cloud Broker MQ resources sub-operator to define a svrconn channel.
- name: Define a svrconn channel
  hosts: all
  collections:
    - ibm.ibm_zos_core
# For playbooks that are run via a z/OS Cloud Broker sub-operator, it is required that gather_facts is disabled.
  gather_facts: no

# Environment, Queue Manager and Channel specific variable files.
  vars_files:
    - vars/env.yml 
    - vars/mq_qmgr.yml
    - vars/mq_svrconn.yml

# Environment variables
  environment: "{{ environment_vars }}"

  tasks:
    - name: Build DEFINE svrconn CHANNEL command
      set_fact:
        define_svrconn_channel_cmd: "{{ mq_qmgr_cpf }} DEFINE CHANNEL({{ mq_channel_name }}) CHLTYPE({{ mq_channel_type }}) DESCR('{{ mq_channel_descr }}') TRPTYPE({{ mq_channel_trp_type }}) {{ mq_channel_replace }}"

    - name: Add LIKE attribute if like channel name is specified
      set_fact:
        define_svrconn_channel_cmd: "{{ define_svrconn_channel_cmd }} LIKE({{ mq_like_channel_name }})"
      when: mq_like_channel_name

    - name: Issue DEFINE svrconn CHANNEL command and register the output
      zos_operator:
        cmd: "{{ define_svrconn_channel_cmd }}"
        verbose: false
      register: define_svrconn_channel_output

    - name: Display output from DEFINE svrconn CHANNEL command
      debug:
        msg: "{{ define_svrconn_channel_output.content }}"

    - name: DEFINE svrconn CHANNEL command succeeded
      debug:
        msg: "Define svrconn channel {{ mq_channel_name }} succeeded"
      when: define_svrconn_channel_output.content is search("CSQ9022I")

    - name: DEFINE svrconn CHANNEL command failed
      fail:
        msg: "Define svrconn channel {{ mq_channel_name }} failed"
      when: define_svrconn_channel_output.content is not search("CSQ9022I")

    - name: Issue DISPLAY svrconn CHANNEL command
      zos_operator:
        cmd: "{{ mq_qmgr_cpf }} DISPLAY {{ mq_channel_type }}({{ mq_channel_name }})"
        verbose: false
      register: display_svrconn_channel_output
      when: define_svrconn_channel_output.content is search("CSQ9022I")

# The output from the display command can be viewed in the Red Hat OpenShift Console.
    - name: Display output from DISPLAY svrconn CHANNEL command
      debug:
        msg: "{{ display_svrconn_channel_output.content }}"
      when: display_svrconn_channel_output

# The following config map code could not be verified on our test machine so it has been commented out. 
# The intent of the code was to save the output of the display command to a config map so that the map 
# could be viewed in the Red Hat OpenShift Console. 
#
#    - name: Create config map for output of DISPLAY svrconn CHANNEL command
#      k8s:
#        state: present
#        definition:
#          apiVersion: v1
#          kind: ConfigMap
#          metadata:
#            name: svrconn_channel_map
#            namespace: default
#          data: "{{ display_svrconn_channel_output.content }}"
...