---
# (c) Copyright IBM Corporation 2023
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

# Playbook file: playbooks/mq_define_qlocal.yml

# This playbook is run via the z/OS Cloud Broker MQ resources sub-operator to define a local queue.
- name: Define a local queue 
  hosts: all
  collections:
    - ibm.ibm_zos_core
    - kubernetes.core
# For playbooks that are run via a z/OS Cloud Broker sub-operator, it is required that gather_facts is disabled.
  gather_facts: no

# Environment, Queue Manager and Queue specific variable files.
  vars_files:
    - vars/env.yml 
    - vars/mq_qmgr.yml
    - vars/mq_qlocal.yml

# Environment variables
  environment: "{{ environment_vars }}"

  tasks:
    - name: Build DEFINE QLOCAL command
      set_fact:
        define_qlocal_cmd: "{{ mq_qmgr_cpf }} DEFINE {{ mq_queue_type }}({{ mq_queue_name }}) DESCR('{{ mq_queue_descr }}') {{ mq_queue_replace }}"

    - name: Add LIKE attribute if like queue name is specified
      set_fact:
        define_qlocal_cmd: "{{ define_qlocal_cmd }} LIKE({{ mq_like_queue_name }})"
      when: mq_like_queue_name

    - name: Issue DEFINE QLOCAL command and register the output
      zos_operator:
        cmd: "{{ define_qlocal_cmd }}"
        verbose: false
      register: define_qlocal_output

    - name: Display output from DEFINE QLOCAL command 
      debug:
        msg: "{{ define_qlocal_output.content }}"

    - name: DEFINE QLOCAL command succeeded
      debug:
        msg: "Define qlocal {{ mq_queue_name }} succeeded"
      # CSQ9022I - normal completion message
      when: define_qlocal_output.content is search("CSQ9022I")

    - name: DEFINE QLOCAL command failed
      fail:
        msg: "Define qlocal {{ mq_queue_name }} failed"
      when: define_qlocal_output.content is not search("CSQ9022I")

    - name: Issue DISPLAY QLOCAL command and register the output
      zos_operator:
        cmd: "{{ mq_qmgr_cpf }} DISPLAY {{ mq_queue_type }}({{ mq_queue_name }})"
        verbose: false
      register: display_qlocal_output
      when: define_qlocal_output.content is search("CSQ9022I")

# The output from the display command can be viewed in the Red Hat OpenShift Console.
    - name: Display output from DISPLAY QLOCAL command
      debug:
        msg: "{{ display_qlocal_output.content }}"
      when: display_qlocal_output

# The following config map code could not be verified on our test machine so it has been commented out. 
# The intent of the code was to save the output of the display command to a config map so that the map 
# could be viewed in the Red Hat OpenShift Console.
#
#    - name: Create config map for output of DISPLAY QLOCAL command
#      k8s:
#        state: present
#        definition:
#          apiVersion: v1
#          kind: ConfigMap
#          metadata:
#            name: local_queue_map
#            namespace: default
#          data: "{{ display_qlocal_output.content }}"
...